# Generated by Django 4.0.6 on 2022-07-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255, unique=True, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал здания',
                'verbose_name_plural': 'Материалы зданий',
            },
        ),
    ]
