# Generated by Django 4.0.6 on 2022-07-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('id',), 'verbose_name': 'Материал здания', 'verbose_name_plural': 'Материалы зданий'},
        ),
    ]
