# Generated by Django 4.0.6 on 2022-07-25 09:11

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_alter_material_options'),
    ]

    operations = [
        CITextExtension(),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='Материал'),
        ),
    ]
