# Generated by Django 4.0.6 on 2022-07-25 15:15

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20220725_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deanery', django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='Деканат')),
            ],
            options={
                'verbose_name': 'Деканат',
                'verbose_name_plural': 'Деканаты',
                'ordering': ('id',),
            },
        ),
    ]
