# Generated by Django 4.0.6 on 2022-07-25 15:19

from django.db import migrations


def fill_deans(apps, schema_editor):
    """Заполнение модели Deanery данными"""
    deans = ('Гуманитарный', 'Физико-математический')
    Deanery = apps.get_model('registry', 'Deanery')

    for dean in deans:
        Deanery.objects.get_or_create(deanery=dean)

class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_deanery'),
    ]

    operations = [
        migrations.RunPython(fill_deans),
    ]
