# Generated by Django 4.0.6 on 2022-07-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_auto_20220725_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deanery',
            old_name='deanery',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target',
            new_name='name',
        ),
    ]
