# Generated by Django 4.0.6 on 2022-07-25 15:37

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_rename_deanery_deanery_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='Департамент')),
                ('boss', models.CharField(max_length=60, verbose_name='Директор')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Телефон')),
                ('deanery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='registry.deanery', verbose_name='Деканат')),
            ],
            options={
                'verbose_name': 'Депарамент',
                'verbose_name_plural': 'Департаменты',
                'ordering': ('id',),
            },
        ),
    ]
