# Generated by Django 4.0.6 on 2022-07-25 15:39

from django.db import migrations


def fill_departments(apps, schema_editor):
    """Заполнение модели Department данными"""
    departments = (
        {
            'name': 'Философия',
            'boss': 'Ячин Сергей Евгеньевич',
            'phone': '+72322652424',
            'deanery': 1,
        },
        {
            'name': 'Социальные науки',
            'boss': 'Кузина Ирина Геннадьевна',
            'phone': '+72322652425',
            'deanery': 1,
        },
        {
            'name': 'Психология',
            'boss': 'Батурина Оксана Сергеевна',
            'phone': '+72322652426',
            'deanery': 1,
        },
        {
            'name': 'История и археология',
            'boss': 'Пахомов Олег Станиславович',
            'phone': '+72322652427',
            'deanery': 1,
        },
    )
    Department = apps.get_model('registry', 'Department')
    Deanery = apps.get_model('registry', 'Deanery')

    for department in departments:
        department['deanery'] = Deanery.objects.get(
            id=department.pop('deanery')
        )
        Department.objects.get_or_create(**department)

class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_department'),
    ]

    operations = [
        migrations.RunPython(fill_departments),
    ]
