# Generated by Django 4.0.6 on 2022-07-26 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_auto_20220725_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='deanery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='registry.deanery', verbose_name='Деканат'),
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Здание')),
                ('land', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь участка')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год постройки')),
                ('wear', models.PositiveSmallIntegerField(verbose_name='Износ (%)')),
                ('flows', models.PositiveSmallIntegerField(verbose_name='Этажи')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%m', verbose_name='Фото здания')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Доп.сведения')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='registry.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
                'ordering': ('id',),
            },
        ),
    ]
