# Generated by Django 4.0.6 on 2022-07-26 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_alter_department_deanery_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='flows',
            new_name='floors',
        ),
    ]
