# Generated by Django 4.0.6 on 2022-07-26 07:46

from django.db import migrations


def fill_buildings(apps, schema_editor):
    """Заполнение модели Building данными"""
    buildings = (
        {
            'name': 'Административное',
            'land': 4000,
            'address': 'ул.Никифорова, 2А',
            'year': 1982,
            'wear': 50,
            'floors': 5,
            'material': 1,
        },
        {
            'name': 'Корпус 1',
            'land': 3000,
            'address': 'ул.Луговая, 59',
            'year': 1985,
            'wear': 20,
            'floors': 3,
            'material': 3,
        },
        {
            'name': 'Корпус 2',
            'land': 3200,
            'address': 'ул.Пограничная, 6',
            'year': 1986,
            'wear': 30,
            'floors': 3,
            'material': 3,
        },
    )
    Building = apps.get_model('registry', 'Building')
    Material = apps.get_model('registry', 'Material')

    for building in buildings:
        building['material'] = Material.objects.get(
            id=building.pop('material')
        )
        Building.objects.get_or_create(**building)

class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_rename_flows_building_floors'),
    ]

    operations = [
        migrations.RunPython(fill_buildings),
    ]
