# Generated by Django 4.0.6 on 2022-07-28 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_auto_20220726_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(null=True, verbose_name='Номер помещения')),
                ('square', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь')),
                ('windows', models.PositiveSmallIntegerField(verbose_name='Кол-во окон')),
                ('heaters', models.PositiveSmallIntegerField(verbose_name='Кол-во обогревателей')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='registry.building', verbose_name='Здание')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to='registry.department', verbose_name='Депаратамент')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to='registry.target', verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ('id',),
            },
        ),
    ]
