# Generated by Django 4.0.6 on 2022-07-28 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to='registry.department', verbose_name='Департамент'),
        ),
    ]
