# Generated by Django 4.0.6 on 2022-07-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_alter_hall_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to='registry.target', verbose_name='Назначение помещения'),
        ),
    ]
