# Generated by Django 4.0.6 on 2022-07-28 08:47

from django.db import migrations


def fill_halls(apps, schema_editor):
    """Заполнение модели Hall данными"""
    halls = (
        {
            'number': 101,
            'square': 48,
            'windows': 5,
            'heaters': 5,
            'target': 1,
            'department': 1,
            'building': 2,
        },
        {
            'number': 202,
            'square': 44,
            'windows': 4,
            'heaters': 4,
            'target': 1,
            'department': 2,
            'building': 2,
        },
        {
            'number': 122,
            'square': 32,
            'windows': 3,
            'heaters': 3,
            'target': 2,
            'department': 3,
            'building': 3,
        },
        {
            'number': 308,
            'square': 46,
            'windows': 4,
            'heaters': 4,
            'target': 4,
            'department': 4,
            'building': 3,
        },
        {
            'number': None,
            'square': 216,
            'windows': 1,
            'heaters': 2,
            'target': 5,
            'department': 4,
            'building': 3,
        },
    )
    Hall = apps.get_model('registry', 'Hall')
    Target = apps.get_model('registry', 'Target')
    Department = apps.get_model('registry', 'Department')
    Building = apps.get_model('registry', 'Building')

    for hall in halls:
        hall['target'] = Target.objects.get(
            id=hall.pop('target')
        )
        hall['department'] = Department.objects.get(
            id=hall.pop('department')
        )
        hall['building'] = Building.objects.get(
            id=hall.pop('building')
        )
        Hall.objects.get_or_create(**hall)


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_alter_hall_target'),
    ]

    operations = [
        migrations.RunPython(fill_halls),
    ]
