# Generated by Django 4.0.6 on 2022-07-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_auto_20220728_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief', models.CharField(max_length=60, verbose_name='Ответственный за имущество')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес проживания')),
                ('experience', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт (лет)')),
            ],
            options={
                'verbose_name': 'Ответственный за имущество',
                'verbose_name_plural': 'Ответственные за имущество',
                'ordering': ('id',),
            },
        ),
    ]
