# Generated by Django 4.0.6 on 2022-07-28 09:40

from django.db import migrations


def fill_chiefs(apps, schema_editor):
    """Заполнение модели Chief данными"""
    chiefs = (
        {
            'chief': 'Иванов',
            'address': 'ул.Никифорова, 56',
            'experience': 2,
        },
        {
            'chief': 'Петров',
            'address': 'ул.Луговая, 22',
            'experience': 3,
        },
        {
            'chief': 'Кошкин',
            'address': 'ул.Пограничная, 9',
            'experience': 3,
        },
        {
            'chief': 'Чайкин',
            'address': 'ул.Приморская, 35',
        },

    )
    Chief = apps.get_model('registry', 'Chief')

    for chief in chiefs:
        Chief.objects.get_or_create(**chief)

class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_chief'),
    ]

    operations = [
        migrations.RunPython(fill_chiefs),
    ]
