# Generated by Django 4.0.6 on 2022-07-28 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0019_auto_20220728_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имущество')),
                ('date_start', models.DateField(default=datetime.date.today, verbose_name='Постановка на учет')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('cost_year', models.PositiveSmallIntegerField(null=True, verbose_name='Год переоценки')),
                ('cost_after', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость после переоценки')),
                ('period', models.PositiveSmallIntegerField(verbose_name='Срок службы')),
                ('chief', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='registry.chief', verbose_name='Ответственный')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='registry.hall', verbose_name='Помещение')),
            ],
            options={
                'verbose_name': 'Имущество',
                'verbose_name_plural': 'Имущество',
                'ordering': ('id',),
            },
        ),
    ]
