# Generated by Django 4.0.6 on 2022-07-28 10:33

import datetime as dt
from django.db import migrations


def fill_units(apps, schema_editor):
    """Заполнение модели Unit данными"""
    units = (
        {
            'name': 'Шкаф',
            'date_start': dt.date(2005, 4, 27),
            'cost': 5600,
            'cost_year': 2020,
            'cost_after': 4700,
            'period': 30,
            'hall': 1,
            'chief': 1,
        },
        {
            'name': 'Обогреватель',
            'date_start': dt.date(2016, 6, 19),
            'cost': 3200,
            'cost_year': 2021,
            'cost_after': 2800,
            'period': 20,
            'hall': 2,
            'chief': 2,
        },
        {
            'name': 'Компьютер',
            'date_start': dt.date(2019, 12, 31),
            'cost': 46000,
            'cost_year': 2022,
            'cost_after': 39500,
            'period': 10,
            'hall': 4,
            'chief': 3,
        },
    )
    Unit = apps.get_model('registry', 'Unit')
    Hall = apps.get_model('registry', 'Hall')
    Chief = apps.get_model('registry', 'Chief')

    for unit in units:
        unit['hall'] = Hall.objects.get(
            id=unit.pop('hall')
        )
        unit['chief'] = Chief.objects.get(
            id=unit.pop('chief')
        )
        Unit.objects.get_or_create(**unit)


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0020_unit'),
    ]

    operations = [
        migrations.RunPython(fill_units),
    ]
