# Generated by Django 4.0.6 on 2022-07-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_auto_20220728_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buildings', to='registry.material', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='department',
            name='deanery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='registry.deanery', verbose_name='Деканат'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to='registry.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Номер помещения'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halls', to='registry.target', verbose_name='Назначение помещения'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='registry.chief', verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='cost_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость после переоценки'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='cost_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год переоценки'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='registry.hall', verbose_name='Помещение'),
        ),
    ]
