# Generated by Django 4.0.6 on 2022-08-10 14:49

import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0023_alter_building_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='floors',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Этажи'),
        ),
        migrations.AlterField(
            model_name='building',
            name='land',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь участка'),
        ),
        migrations.AlterField(
            model_name='building',
            name='wear',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Износ (%)'),
        ),
        migrations.AlterField(
            model_name='chief',
            name='experience',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Опыт (лет)'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='square',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Назначение помещения'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
        ),
    ]
